// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVVIb1gZ1qHEnDWq11Eo9-pk1rWF0e08',
    appId: '1:632958302905:web:ef6e6ed02db6e9084f3968',
    messagingSenderId: '632958302905',
    projectId: 'yume-8c67e',
    authDomain: 'yume-8c67e.firebaseapp.com',
    storageBucket: 'yume-8c67e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5dW05eHPqB8myDNSE28CCWrXbw2R77XU',
    appId: '1:632958302905:android:49dcaf5bad70b25c4f3968',
    messagingSenderId: '632958302905',
    projectId: 'yume-8c67e',
    storageBucket: 'yume-8c67e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8AvO6pb7chHiMiE-0wQpL3_gJjzqDh0Y',
    appId: '1:632958302905:ios:4cfca48a6bd11c5b4f3968',
    messagingSenderId: '632958302905',
    projectId: 'yume-8c67e',
    storageBucket: 'yume-8c67e.appspot.com',
    iosBundleId: 'com.example.yume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8AvO6pb7chHiMiE-0wQpL3_gJjzqDh0Y',
    appId: '1:632958302905:ios:4cfca48a6bd11c5b4f3968',
    messagingSenderId: '632958302905',
    projectId: 'yume-8c67e',
    storageBucket: 'yume-8c67e.appspot.com',
    iosBundleId: 'com.example.yume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVVIb1gZ1qHEnDWq11Eo9-pk1rWF0e08',
    appId: '1:632958302905:web:9bf71652d8e425024f3968',
    messagingSenderId: '632958302905',
    projectId: 'yume-8c67e',
    authDomain: 'yume-8c67e.firebaseapp.com',
    storageBucket: 'yume-8c67e.appspot.com',
  );

}